version: '3.8'

services:
  # Main application service
  openai-agents-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - OPIK_URL=http://opik-backend:3003/api
    depends_on:
      - opik-backend
      - opik-frontend
    networks:
      - opik-network
    volumes:
      - .:/app
    restart: unless-stopped

  # Opik Backend Services
  opik-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: opik
      MYSQL_DATABASE: opik
      MYSQL_USER: opik
      MYSQL_PASSWORD: opik
    volumes:
      - opik_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - opik-network
    restart: unless-stopped

  opik-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - opik-network
    restart: unless-stopped

  opik-clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DB: opik
      CLICKHOUSE_USER: opik
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: opik
    volumes:
      - opik_clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - opik-network
    restart: unless-stopped

  opik-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: opik
      MINIO_ROOT_PASSWORD: opikpassword
    volumes:
      - opik_minio_data:/data
    ports:
      - "9001:9001"
      - "9002:9000"
    networks:
      - opik-network
    restart: unless-stopped

  opik-backend:
    image: cometml/opik-backend:latest
    environment:
      DATABASE_URL: mysql://opik:opik@opik-mysql:3306/opik
      REDIS_URL: redis://opik-redis:6379
      CLICKHOUSE_URL: http://opik:opik@opik-clickhouse:8123/opik
      MINIO_ENDPOINT: http://opik-minio:9000
      MINIO_ACCESS_KEY: opik
      MINIO_SECRET_KEY: opikpassword
    depends_on:
      - opik-mysql
      - opik-redis
      - opik-clickhouse
      - opik-minio
    ports:
      - "3003:3003"
    networks:
      - opik-network
    restart: unless-stopped

  opik-frontend:
    image: cometml/opik-frontend:latest
    environment:
      OPIK_BACKEND_URL: http://opik-backend:3003
    depends_on:
      - opik-backend
    ports:
      - "5173:5173"
    networks:
      - opik-network
    restart: unless-stopped

volumes:
  opik_mysql_data:
  opik_clickhouse_data:
  opik_minio_data:

networks:
  opik-network:
    driver: bridge
